
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\CadastrarCliente")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1356x826")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 826,
    width = 1356,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    973.0,
    -1.0,
    976.000000035664,
    826.0000289607269,
    fill="#16453F",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1024.0,
    y=333.0,
    width=284.0,
    height=160.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=1024.0,
    y=46.0,
    width=284.0,
    height=160.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1024.0,
    y=620.0,
    width=284.0,
    height=160.0
)

canvas.create_rectangle(
    35.0,
    29.0,
    945.0,
    798.0,
    fill="#16453F",
    outline="")

canvas.create_text(
    399.0,
    91.0,
    anchor="nw",
    text="Insira os dados do cliente",
    fill="#A6F6AF",
    font=("Inter SemiBold", 14 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=385.0,
    y=732.0,
    width=213.0,
    height=63.0
)

canvas.create_text(
    311.0,
    46.0,
    anchor="nw",
    text="Cadastrar cliente",
    fill="#F9F9F9",
    font=("Inter Bold", 40 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    494.0,
    175.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EEF4EC",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=84.0,
    y=151.0,
    width=820.0,
    height=47.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    286.0,
    259.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#EEF4EC",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=86.0,
    y=234.0,
    width=400.0,
    height=48.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    286.0,
    428.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#EEF4EC",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=86.0,
    y=403.0,
    width=400.0,
    height=48.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    703.0,
    428.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#EEF4EC",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=502.0,
    y=403.0,
    width=402.0,
    height=48.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    703.0,
    259.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#EEF4EC",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=503.0,
    y=234.0,
    width=400.0,
    height=48.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    494.0,
    515.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#EEF4EC",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=84.0,
    y=491.0,
    width=820.0,
    height=47.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    494.0,
    599.5,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#EEF4EC",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=84.0,
    y=575.0,
    width=820.0,
    height=47.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    494.0,
    691.5,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#EEF4EC",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=84.0,
    y=667.0,
    width=820.0,
    height=47.0
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    495.0,
    339.5,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#EEF4EC",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=86.0,
    y=315.0,
    width=818.0,
    height=47.0
)

canvas.create_text(
    84.0,
    629.0,
    anchor="nw",
    text="Confirmar senha ",
    fill="#EEF4EC",
    font=("Inter SemiBold", 32 * -1)
)

canvas.create_text(
    84.0,
    542.0,
    anchor="nw",
    text="Senha",
    fill="#EEF4EC",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_text(
    502.0,
    370.0,
    anchor="nw",
    text="Data de nascimento",
    fill="#EEF4EC",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_text(
    84.0,
    369.0,
    anchor="nw",
    text="Telefone",
    fill="#EEF4EC",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_text(
    84.0,
    455.0,
    anchor="nw",
    text="Endereço",
    fill="#EEF4EC",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_text(
    86.0,
    115.0,
    anchor="nw",
    text="Nome",
    fill="#EEF4EC",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_text(
    84.0,
    200.0,
    anchor="nw",
    text="CPF",
    fill="#EEF4EC",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_text(
    86.0,
    284.0,
    anchor="nw",
    text="Email",
    fill="#EEF4EC",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_text(
    503.0,
    200.0,
    anchor="nw",
    text="CEP",
    fill="#EEF4EC",
    font=("Inter SemiBold", 30 * -1)
)
window.resizable(False, False)
window.mainloop()
