
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1356x826")
window.configure(bg = "#E4E6E5")


canvas = Canvas(
    window,
    bg = "#E4E6E5",
    height = 826,
    width = 1356,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    124.99999838826625,
    47.99999837707202,
    image=image_image_1
)

canvas.create_rectangle(
    117.0,
    85.0,
    1253.0,
    168.0,
    fill="#16453F",
    outline="")

canvas.create_rectangle(
    117.0,
    237.0,
    1253.0,
    279.0,
    fill="#C9CDCA",
    outline="")

canvas.create_rectangle(
    117.0,
    413.0,
    699.0,
    455.0,
    fill="#C9CDCA",
    outline="")

canvas.create_rectangle(
    117.0,
    295.0,
    1253.0,
    333.0,
    fill="#C9CDCA",
    outline="")

canvas.create_rectangle(
    722.0,
    349.0,
    1253.0,
    393.0,
    fill="#C9CDCA",
    outline="")

canvas.create_rectangle(
    118.0,
    349.0,
    699.0,
    392.0,
    fill="#C9CDCA",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=522.0,
    y=534.0,
    width=312.0,
    height=59.0
)

canvas.create_text(
    130.0,
    299.0,
    anchor="nw",
    text="Senha: ********",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    125.0,
    245.0,
    anchor="nw",
    text="Nome: ",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    125.0,
    421.0,
    anchor="nw",
    text="Registro de Vendedores",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    118.0,
    189.0,
    anchor="nw",
    text="Dados da Clínica",
    fill="#000000",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    394.0,
    89.0,
    anchor="nw",
    text="Dados da empresa",
    fill="#FFFFFF",
    font=("Inter Bold", 64 * -1)
)

canvas.create_text(
    150.0,
    34.0,
    anchor="nw",
    text="Voltar",
    fill="#000000",
    font=("Inter SemiBold", 26 * -1)
)

canvas.create_text(
    733.0,
    358.0,
    anchor="nw",
    text="CNPJ",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    567.0,
    358.0,
    anchor="nw",
    text="Adicionar",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    567.0,
    420.0,
    anchor="nw",
    text="Adicionar",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_rectangle(
    722.0,
    413.0,
    1253.0,
    455.0,
    fill="#C9CDCA",
    outline="")

canvas.create_text(
    731.0,
    421.0,
    anchor="nw",
    text="Registro de Clientes",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    1133.0,
    420.0,
    anchor="nw",
    text="Adicionar",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    1174.0,
    299.0,
    anchor="nw",
    text="Editar",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    128.0,
    358.0,
    anchor="nw",
    text="E-mail",
    fill="#000000",
    font=("Inter", 24 * -1)
)
window.resizable(False, False)
window.mainloop()
