
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1356x826")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 826,
    width = 1356,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    404.0,
    137.0,
    952.0,
    689.0,
    fill="#16453F",
    outline="")

canvas.create_text(
    624.0,
    187.0,
    anchor="nw",
    text="Login",
    fill="#EEF4EC",
    font=("Inter Bold", 40 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=578.0,
    y=509.0,
    width=194.0,
    height=80.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    678.0,
    320.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=474.0,
    y=280.0,
    width=408.0,
    height=78.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    678.0,
    431.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=474.0,
    y=391.0,
    width=408.0,
    height=78.0
)

canvas.create_text(
    439.0,
    627.0,
    anchor="nw",
    text="Esqueceu a senha?",
    fill="#EEF4EC",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    711.0,
    627.0,
    anchor="nw",
    text="Não tem conta?",
    fill="#EEF4EC",
    font=("Inter Bold", 24 * -1)
)
window.resizable(False, False)
window.mainloop()
